version: "3.9"

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  beat:
    build: .
    restart: always
    command: celery -A app.tasks workers --loglevel=info
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
