version: "3.9"

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
#    restart: always
    command: celery -A celery_app.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  beat:
    build: .
#    restart: always
    command: celery -A celery_app.celery beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - worker
    volumes:
      - ./celerybeat-schedule:/app/celerybeat-schedule
