version: "3.9"

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    restart: on-failure
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./logs:/bot/logs

  beat:
    build: .
    restart: on-failure
    command: celery -A app.celery_app.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - worker
