version: "3.9"

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    restart: always
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./logs:/bot/logs

#  beat:
#    build: .
##    restart: always
#    command: celery -A celery_app.celery beat --loglevel=info
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - worker
#    volumes:
#      - ./celerybeat-schedule:/app/celerybeat-schedule

  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m app.main
    depends_on:
      - redis
      - worker
    env_file:
      - .env
    volumes:
      - ./logs:/bot/logs
