version: "3.9"

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - jobbot-net

  worker:
    build: .
    restart: on-failure
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - selenium
    volumes:
      - ./logs:/bot/logs
    networks:
      - jobbot-net

  beat:
    build: .
    restart: on-failure
    command: celery -A app.celery_app.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - selenium
    networks:
      - jobbot-net

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    networks:
      - jobbot-net

networks:
  jobbot-net:
    driver: bridge
